name: Daily Commit Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Update for 23f1003184@ds.study.iitm.ac.in
        run: |
          git config user.name "bot"
          git config user.email "23f1003184@ds.study.iitm.ac.in"
          date >> activity.txt
          git add activity.txt
          git commit -m "Update $(date +%F)" || exit 0
          git push
